backend:
  name: git-gateway
  branch: main # Or master, depending on your default branch name

media_folder: "assets/images/uploads" # Folder where uploaded images will be stored
public_folder: "/assets/images/uploads" # The public path to the media folder

collections:
  - name: "posts" # API endpoint, e.g., /admin/collections/posts
    label: "News & Insights" # UI Label
    folder: "_posts" # Folder where the markdown files for articles will be stored
    create: true # Allow users to create new articles
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new articles
    fields: # Defines the fields in the editor for each article
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "ASPL Fusion"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: true, hint: "A brief summary that will appear in the news listing page"}
      - {label: "Category", name: "category", widget: "select", options: ["Company News", "Technology Updates", "Industry Insights", "Events", "Press Releases"], required: true}
      - {label: "Body", name: "body", widget: "markdown"}